services:
  - type: web
    name: ecommerce
    env: php
    region: oregon
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      npm install
      npm run build
      php artisan key:generate
      php artisan migrate --force
      php artisan config:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ecommerce.onrender.com
